[tool.poetry]
name = "jb-core"
version = "0.1.0"
description = ""
authors = ["OpenNyAI Team <opennyai@googlegroups.com>"]
readme = "README.md"
packages = [{include = "jugalbandi"}]

[tool.poetry.dependencies]
python = ">=3.10, <4.0.0"
cachetools = "^5.3.1"
types-cachetools = "^5.3.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
