[tool.poetry]
name = "jb-translator"
version = "0.1.0"
description = ""
authors = ["OpenNyAI Team <opennyai@googlegroups.com>"]
readme = "README.md"
packages = [{include = "jugalbandi/translator"}]

[tool.poetry.dependencies]
python = ">=3.12, <4.0.0"
google-cloud-translate = "^3.14.0"
httpx = "^0.26.0"
jb-core = {path = "../jb-core", develop = true}
python-dotenv = "^1.0.1"
aiohttp = "3.9.3"
certifi = "2023.11.17"
grpcio = "1.60.0"
urllib3 = "2.2.0"


[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
mypy = "^1.8.0"
flake8 = "^7.0.0"
poethepoet = "^0.24.4"
pytest = "^8.0.0"
pytest-asyncio = "^0.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poe.tasks.lint]
shell = """
black jugalbandi tests
flake8 jugalbandi tests
mypy jugalbandi tests
"""
interpreter = "bash"
help = "format, lint, typecheck"


[tool.poe.tasks.test]
cmd = "python -m pytest -vv -o log_cli=1 -o log_cli_level=INFO -W 'ignore::DeprecationWarning' $FILE"
args = [{name="FILE", default="tests", positional=true}]
help = "run tests using pytest"
